name: Go Build

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当有 pull request 到 main 分支时触发

jobs:
  build:
    name: Build and package Go binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]  # 需要打包的操作系统
        goarch: [amd64]  # 目标架构
        include:
          - goos: windows
            goarch: amd64
            ext: .exe
          - goos: linux
            goarch: amd64
            ext: ""
          - goos: darwin
            goarch: amd64
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'  # 设置你需要的 Go 版本

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o findos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: findos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
          path: findos-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
